
package https.www_supernotariado_gov_co.services.bachue.ee.alertatierras.v1;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import co.gov.supernotariado.bachue.portalgeografico.ws.ClienteJSON;
import https.www_supernotariado_gov_co.schemas.bachue.ee.alertatierras.consultarmapapredioinfocatastral.v1.TipoEntradaConsultarMapaPredioInfoCatastral;
import https.www_supernotariado_gov_co.schemas.bachue.ee.alertatierras.consultarmapapredioinfocatastral.v1.TipoSalidaConsultarMapaPredioInfoCatastral;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "BS_SUT_GI_MapasPort", serviceName = "BS_SUT_GI_Mapas", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/alertaTierras/v1", wsdlLocation = "/wsdls/BS_SUT_GI_Mapas.wsdl", endpointInterface = "https.www_supernotariado_gov_co.services.bachue.ee.alertatierras.v1.BSSUTGIMapas")
@BindingType("http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class BS_SUT_GI_Mapas_BS_SUT_GI_MapasPortImpl implements BSSUTGIMapas {

	private static final String ARCGIS_BASE_URL = "http://192.168.36.18:6080/arcgis/rest/services/san_vicente/San_Vicente/MapServer";
	private static final String ARCGIS_EXPORT_URL = "http://192.168.36.18:6080/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/execute";

	public BS_SUT_GI_Mapas_BS_SUT_GI_MapasPortImpl() {
	}

	/**
	 * Metodo que acepta un numero catastral y devuelve una clase de tipo
	 * SalidaConsultarMapaPredioInfoCatastral
	 * 
	 * @param entrada
	 * @return returns
	 *         https.www_supernotariado_gov_co.schemas.bachue.ee.alertatierras.consultarmapapredioinfocatastral.v1.TipoSalidaConsultarMapaPredioInfoCatastral
	 */
	public TipoSalidaConsultarMapaPredioInfoCatastral consultarMapaPredioInfoCatastral(
			TipoEntradaConsultarMapaPredioInfoCatastral entrada) {
		TipoSalidaConsultarMapaPredioInfoCatastral salida = new TipoSalidaConsultarMapaPredioInfoCatastral();
		try {
			String result = ClienteJSON.getMap(entrada.getNumeroCatastral(), ARCGIS_BASE_URL, ARCGIS_EXPORT_URL);
			if (result.isEmpty()) {
				salida.setCodigo("ERROR");
				salida.setMensaje("Error al generar la imágen");
				salida.setPNG(null);
			} else {
				salida.setCodigo("200");
				salida.setMensaje("Consulta exitosa!");
				salida.setPNG(result);
			}
		} catch (Exception ex) {
			salida.setCodigo("402");
			salida.setMensaje("Error al generar la imágen");
			salida.setPNG(null);
		}
		return salida;
	}

}
